### ISSUE TITLE
Not an issue, just a question!

### ISSUE THREAD

**Issue by rident** [DevotedMC/HiddenOre#33]
So I'm trying to configure HiddenOre to mimic Vanilla properties, like when you mine coal ore you receive coal and you can Fortune it as well, or silk touch it even, but I haven't been able to successfully configure it. And I was wondering if there are there any config examples of this? I'm using the 1.12 version currently.

Any assistance would be appreciated!
Thank you.

**Comment by ProgrammerDan** [comment]
Sure, it is possible with some clever tools work and config work. 

I assume from the silk touch comment that you use Drops and not Transformations?

**Comment by rident** [comment]
Yeah, I've been attempting it with drops, but I haven't been able to get it to work. I haven't even gotten the ore blocks to drop the ore instead of the block yet. The closest I've gotten was having stone drop diamonds, which was clearly not the intended outcome.

**Comment by ProgrammerDan** [comment]
Oh strange, can you share what you have so far? Feel free to shoot me an email with it if you've got secret ratios that you don't want shared.

**Comment by rident** [comment]
Sorry, I may of misunderstood your other question. What I've been trying to have is for stone to transform into ore blocks and then have those ore blocks drop the actual ore, and not ore blocks when broken, other than if they have silk touch. And if they have Fortune, to increase the ore drop chance like you'd see in Vanilla minecraft.

I imagine having it just be drops, you would just include something along the lines of the code I'll include below to stone, but to have stone transformation into ore and then have those transformations drop ore, instead of the actual block, is where I'm getting lost, especially when you have to consider enchantments.

```
drops:
   iron_ore:
    package:
     - ==: org.bukkit.inventory.ItemStack
       type: IRON_ORE
       amount: 1
    tools:
       - wood_pickaxe
       - stone_pickaxe
       - iron_pickaxe
       - diamond_pickaxe
    state: conditions
    minY: 1
    maxY: 255
    chance: 0.005
    minAmount: 1
    maxAmount: 10
    dropIfTransformFails: false
```

And I've been saving over my config trying to figure out how this would even work, so unfortunately I don't have one I can really share, but I've been working off of the civclassic config: https://github.com/CivClassic/HiddenOre/blob/master/src/main/resources/config-civclassic.yml
