### ISSUE TITLE
Item Meta renamed items as drops poops out a lot of bad things.

### ISSUE THREAD

**Issue by Convoy20** [DevotedMC/HiddenOre#36]
```
         meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            display-name: &6Iron Mining Clue 1
            lore:
```

Causes the displayname to not look good, bunch of brackets and variables listed in the name.
