### ISSUE TITLE
Add special drop prevention

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/HiddenOre#7]
Add a "suppressDrops" boolean config to a block type. If set, ignores rest of config for that block type, and suppresses all drops from that type of block universally, regardless of tool.

**Comment by ProgrammerDan** [comment]
Until this is added you can emulate that behavior by adding configs for each ore type as follows:

```
 COAL_ORE:
  allTypes: true
  dropMultiple: false
  drops:
   STONE:
    tools:
     - WOOD_PICKAXE
     - STONE_PICKAXE
     - IRON_PICKAXE
     - GOLD_PICKAXE
     - DIAMOND_PICKAXE
    minY: 0
    maxY: 256
    chance: 1.0
    minAmount: 1
    maxAmount: 1
```
